### ISSUE TITLE
Add example image

### ISSUE THREAD

**Issue by hwclass** [bilalcorbacioglu/Steganography#1]
Hi,

I think it could be nice to add an example image which is optimized with this library.

Thanks.

Baris

**Comment by bilalcorbacioglu** [comment]
Hi,

Thanks for Your suggestion. Most recently, I'll make a small sample.

**Comment by bilalcorbacioglu** [comment]
Hello @hwclass ,

Sorry, it was a bit late.

I added a little test. Code review this, I cleaned the code.

In the next stage ' pixel to image converter ' and I will make the code more readable.
